// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package db

import (
	"context"
	"database/sql"
)

const clearManualBalance = `-- name: ClearManualBalance :exec
UPDATE accounts SET manual_balance = NULL WHERE id = ?
`

func (q *Queries) ClearManualBalance(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, clearManualBalance, id)
	return err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (name, type, currency, institution)
VALUES (?, ?, ?, ?)
RETURNING id, name, type, currency, institution, manual_balance, created_at
`

type CreateAccountParams struct {
	Name        string
	Type        string
	Currency    string
	Institution string
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount,
		arg.Name,
		arg.Type,
		arg.Currency,
		arg.Institution,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.Institution,
		&i.ManualBalance,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts WHERE id = ?
`

func (q *Queries) DeleteAccount(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAccount, id)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, name, type, currency, institution, manual_balance, created_at FROM accounts WHERE id = ?
`

func (q *Queries) GetAccount(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.Institution,
		&i.ManualBalance,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountBalance = `-- name: GetAccountBalance :one
SELECT COALESCE(SUM(amount), 0) AS balance
FROM transactions
WHERE account_id = ?
`

func (q *Queries) GetAccountBalance(ctx context.Context, accountID int64) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getAccountBalance, accountID)
	var balance interface{}
	err := row.Scan(&balance)
	return balance, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, name, type, currency, institution, manual_balance, created_at FROM accounts ORDER BY type, name
`

func (q *Queries) ListAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Currency,
			&i.Institution,
			&i.ManualBalance,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setManualBalance = `-- name: SetManualBalance :exec
UPDATE accounts SET manual_balance = ? WHERE id = ?
`

type SetManualBalanceParams struct {
	ManualBalance sql.NullInt64
	ID            int64
}

func (q *Queries) SetManualBalance(ctx context.Context, arg SetManualBalanceParams) error {
	_, err := q.db.ExecContext(ctx, setManualBalance, arg.ManualBalance, arg.ID)
	return err
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts SET name = ?, type = ?, currency = ?, institution = ?
WHERE id = ?
RETURNING id, name, type, currency, institution, manual_balance, created_at
`

type UpdateAccountParams struct {
	Name        string
	Type        string
	Currency    string
	Institution string
	ID          int64
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, updateAccount,
		arg.Name,
		arg.Type,
		arg.Currency,
		arg.Institution,
		arg.ID,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Currency,
		&i.Institution,
		&i.ManualBalance,
		&i.CreatedAt,
	)
	return i, err
}
