// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Account struct {
	ID        int64
	Name      string
	Type      string
	Currency  string
	CreatedAt time.Time
}

type Transaction struct {
	ID          int64
	AccountID   int64
	Amount      int64
	Description string
	Date        time.Time
	CreatedAt   time.Time
}
