// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	ID            int64
	Name          string
	Type          string
	Currency      string
	Institution   string
	ManualBalance sql.NullInt64
	CreatedAt     time.Time
}

type AccountSnapshot struct {
	ID        int64
	AccountID int64
	Date      time.Time
	Balance   int64
	CreatedAt time.Time
}

type Transaction struct {
	ID          int64
	AccountID   int64
	Amount      int64
	Description string
	Date        time.Time
	CreatedAt   time.Time
}
