// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: snapshots.sql

package db

import (
	"context"
	"time"
)

const createSnapshot = `-- name: CreateSnapshot :exec
INSERT INTO account_snapshots (account_id, date, balance)
VALUES (?, ?, ?)
ON CONFLICT(account_id, date) DO UPDATE SET balance = excluded.balance
`

type CreateSnapshotParams struct {
	AccountID int64
	Date      time.Time
	Balance   int64
}

func (q *Queries) CreateSnapshot(ctx context.Context, arg CreateSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, createSnapshot, arg.AccountID, arg.Date, arg.Balance)
	return err
}

const hasSnapshotForDate = `-- name: HasSnapshotForDate :one
SELECT COUNT(*) FROM account_snapshots WHERE date = ?
`

func (q *Queries) HasSnapshotForDate(ctx context.Context, date time.Time) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasSnapshotForDate, date)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listAllSnapshots = `-- name: ListAllSnapshots :many
SELECT id, account_id, date, balance, created_at FROM account_snapshots ORDER BY date DESC, account_id
`

func (q *Queries) ListAllSnapshots(ctx context.Context) ([]AccountSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, listAllSnapshots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountSnapshot
	for rows.Next() {
		var i AccountSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Date,
			&i.Balance,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
